name: cinematix
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  intl: ^0.19.0
  equatable: ^2.0.5
  go_router: ^14.1.3
  provider: ^6.1.2
  infinite_scroll_pagination: ^4.0.0
  easy_debounce: ^2.0.3
  flutter_flavor: ^3.1.3
  fast_cached_network_image: ^1.2.9
  uuid: ^4.4.2
  path_provider: ^2.1.4
  shimmer_animation: ^2.2.1
  share_plus: ^10.1.2
  page_route_animator: ^1.0.4
  talker: ^4.5.2
  talker_logger: ^4.5.2
  talker_flutter: ^4.5.2
  talker_dio_logger: ^4.5.2
  talker_bloc_logger: ^4.5.2
  nil: ^1.1.1
  get_it: ^8.0.3
  geolocator: ^13.0.2
  adaptive_theme: ^3.6.0
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  build_runner: ^2.1.11
  monarch: ^3.8.1
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/payment_logo/

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon.png"
  android: true
  ios: true
  ios_content_mode: center
  android_gravity: center
