name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  drift: ^2.18.0
  hive: ^2.2.3
  objectbox: ^4.0.1
  sqlite3: ^2.4.3
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9
  floor_generator: ^1.5.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
