name: Local CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  
  run_simulator:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: pubspec.yaml 
        channel: 'stable'

    - name: Run Simulator
      run: fvm flutter run --target=lib/main_dev.dart -d iPhone
