name: Main CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install Apple Certificate
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch 
        
    - name: Fix iOS deployment targets
      run: |
        cd ios
        chmod +x dev_target_fix.sh
        ./dev_target_fix.sh
        cd ..

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: pubspec.yaml 
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Install iOS platform tools
      run: |
        flutter config --enable-ios
        flutter precache --ios

    - name: Build
      run: |
        flutter clean
        flutter pub get
        cd ios
        pod install --repo-update
        cd ..
        flutter build ipa --release --no-codesign --target=lib/main_prod.dart

  build_android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: pubspec.yaml 
        channel: 'stable'

    # - name: Set up JDK
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '11'  # Java 11 is required for Flutter

    - name: Install Android SDK and NDK
      uses: android-actions/setup-android@v3

    - name: Check Flutter
      run: flutter doctor

    - name: Install dependencies
      run: flutter pub get

    - name: Build
      run: flutter build apk --release --target-platform=android-arm64 --target=lib/main_prod.dart
  # test:
  #   runs-on: macos-latest
  #   needs: build

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Set up Flutter
  #     uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: '3.24.5'
  #       channel: 'stable'

  #   - name: Run tests
  #     run: flutter test

  # run_simulator:
  #   runs-on: macos-latest 

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Set up Flutter
  #     uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version-file: pubspec.yaml 
  #       channel: 'stable'

  #   - name: Run Simulator
  #     run: flutter run --target=lib/main_prod.dart -d iPhone
